### ISSUE TITLE
Add sax-ts to Deno third-party index

### ISSUE THREAD

**Issue by MikaelPorttila** [Maxim-Mazurok/SAX-TypeScript#3]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Publish this splendid piece of port on the [Deno's third party index](https://deno.land/x/#add)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Maxim-Mazurok** [comment]
Thank you for warm words :)
I don't actively maintain this lib, there are a lot of `any`s, but at least it works with deno and passes all tests.
I recently thought about publishing to the index, but wasn't sure if anyone is interested. Thank you very much for your interest :)
I just published it: https://deno.land/x/sax_ts
Let me know how it works for you!

**Comment by MikaelPorttila** [comment]
Works great - Thank you!
I haven't ran into any issues yet when parsing XML (RSS feeds) and there was no problem with accessing your lib through the Deno third party index. 👍

**Comment by Maxim-Mazurok** [comment]
Glad it helped 😊
