### ISSUE TITLE
Is it possible to pause parsing and events emitting?

### ISSUE THREAD

**Issue by dobromyslov** [Maxim-Mazurok/SAX-TypeScript#4]
**Is your feature request related to a problem? Please describe.**
Can't synchronously parse XML with nested async/await callbacks with sax-js (https://github.com/isaacs/sax-js).

**Describe the solution you'd like**
Looking for another sax lib which supports pause/resume parsing and events for synchronous XML processing with nested async/await callbacks.

**Describe alternatives you've considered**
Found one solution https://github.com/leoz/sax-parser but it does not support stream processing.

**Additional context**
Callback example:
```
console.log('Start');
await new Promise<void>(async (resolve) => {
  await new Promise<void>((resolve1) => {
    for (let i = 0; i < 1000000000; i++) {
    }
    console.log('First Level Promise End');
    resolve1();
  });
  console.log('Second Level Promise End');
  resolve();
});
```

**Comment by dobromyslov** [comment]
Looks like https://github.com/sindresorhus/emittery with `emitSerial` along with input stream pause/resume could do the trick. Will give it a try.

**Comment by Maxim-Mazurok** [comment]
Привет :)
Thank you for your interest in this project!
This is (for the most part) is just a port of isaacs/sax-js library.
If what you're looking for is not present in isaacs/sax-js, then it's most likely not present in Maxim-Mazurok/sax-ts.

Regarding your question, it's kind of the point of this library that it's not synchronous.
You'll have to create your own wrapper to make it work as you want.
You can look at NPM for packages that depend on isaacs/sax-js, some of them will give you an idea of how to create such a wrapper.

**Comment by dobromyslov** [comment]
Спасибо, Максим. 

Found a cool lib `saxes` (https://github.com/lddubeau/saxes) written in TypeScript. 
Also found an async/await solution from the exceljs developer described here https://github.com/lddubeau/saxes/issues/32#issuecomment-640493042
