### ISSUE TITLE
JSR Repository support

### ISSUE THREAD

**Issue by MikaelPorttila** [Maxim-Mazurok/SAX-TypeScript#8]
**Is your feature request related to a problem? Please describe.**
The folks over at Deno has just released the public beta of the JSR repository (https://jsr.io/) which will be a new way to distribute Deno packages. (They have stated that Denoland/X will NOT be replaced).

**Describe the solution you'd like**
Like most populare Deno packages, I'd like to see the sax-ts package available far and wide on JSR.

**Reasoning**
JSR has one major downside which is no support for HTTPS imports, but luckily sax-ts does not use those today which makes a JSR-release easier.

Projects using ts-sax today are most likely importing the project using HTTPS imports which give them a hard time transitioning to JSR until sax-ts or any other parser starts distributing through the new platform.

**Comment by Maxim-Mazurok** [comment]
Hi @MikaelPorttila thanks for raising this :)

I haven't been using Deno in a while, and pleasantly surprised that you're using it, and that it's actually marked as "Very Popular" on [denoland](https://deno.land/x/sax_ts) :)

Publishing seems easy enough, I'll try that now, cheers!

**Comment by Maxim-Mazurok** [comment]
Done, published to https://jsr.io/@maxim-mazurok/sax-ts
Please let me know if it works for you!

Also, I would appreciate it if you could try if https://deno.land/x/sax_ts still works as well, would hate to break existing users...

Consider giving this repo a star if you found it useful :) Cheers!
